#!/bin/bash

export FILEID='1rvMyY_A3YfbiNLWdRKmVVmAijUzBeMTn'
wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=$FILEID' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=$FILEID" -O lin_data.zip && rm -rf /tmp/cookies.txt
unzip lin_data.zip -d ~
rm lin_data.zip

pip install pipenv
pipenv install
